export const ROLE_ADMINISTRATOR = 'administrator'
export const ROLE_TEACHER = 'teacher'
export const ROLE_LIBRARIAN = 'librarian'
export const ROLE_BASE = 'base'

export const STATUS_IN_PROCESSING = 'В обработке'
export const STATUS_ACCEPTED = 'Принято'
export const STATUS_REFUSED = 'Отказано'
export const STATUS_DONE = 'Выполнено'
export const STATUS_PUBLISHING = 'Передано в издательство'
export const STATUS_ORDER = 'Добавлено в заказ'
